name: ambeinte_stereo_884
description: "Ambiente Stereo 884"
publish_to: 'none'

version: 2.0.8+12

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Audio
  volume_controller: ^3.4.0
  audio_session: ^0.2.2
  just_audio: ^0.10.5 

  # Controles en pantalla de bloqueo y notificaciones
  rxdart: ^0.28.0 

  # HTTP
  http: ^1.2.2

  # HTML Parsing
  html: ^0.15.4
  
  # URL Launcher
  url_launcher: ^6.3.1
  
  # WebView
  webview_flutter: ^4.4.0
  
  # Firebase
  cloud_firestore: ^6.0.3
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  firebase_remote_config: ^6.1.0
  
  # Icons
  cupertino_icons: ^1.0.8

  #image para mejor rendimiento de imagenes
  cached_network_image: ^3.3.1

  #Obtener la versión automáticamente
  package_info_plus: ^9.0.0

  # Compartir contenido
  share_plus: ^7.2.1

  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Lints
  flutter_lints: ^6.0.0
  
  # Launcher Icons
  flutter_launcher_icons: ^0.14.4

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.8


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
