name: ambeinte_stereo_884
description: "Ambiente Stereo 884"
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Audio
  volume_controller: ^3.4.0
  
  # Radio streaming
  # radio_player: ^2.1.0
  just_audio: ^0.10.5 

  # Controles en pantalla de bloqueo y notificaciones
  # audio_service: ^0.18.15
  rxdart: ^0.28.0 

  # HTTP
  http: ^1.1.0

  # HTML Parsing
  html: ^0.15.4
  
  # URL Launcher
  url_launcher: ^6.2.4
  
  # WebView
  webview_flutter: ^4.2.2
  
  # Firebase
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2

  # Icons
  cupertino_icons: ^1.0.8

  #image para mejor rendimiento de imagenes
  cached_network_image: ^3.3.1

  #Obtener la versión automáticamente
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Lints
  flutter_lints: ^6.0.0
  
  # Launcher Icons
  flutter_launcher_icons: ^0.14.4

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.8


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
